# Generated by Django 4.0.3 on 2022-03-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Marca')),
                ('sede', models.CharField(max_length=50, verbose_name='Sede')),
            ],
        ),
    ]
